[package]
name = "private_counter"
type = "contract"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages", tag="aztec-packages-v0.16.7", directory="yarn-project/aztec-nr/aztec" }

# These ones are helpers for private state:
value_note = { git="https://github.com/AztecProtocol/aztec-packages", tag="aztec-packages-v0.16.7", directory="yarn-project/aztec-nr/value-note"}
easy_private_state = { git="https://github.com/AztecProtocol/aztec-packages", tag="aztec-packages-v0.16.7", directory="yarn-project/aztec-nr/easy-private-state"}
