name: CI
on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.2
        with:
          toolchain: 0.6.0

      - name: Run Nargo test
        run: |
          cd circuits/examples
          failed=0

          for d in */ ; do
            echo ""
            echo "ğŸƒâ€â™€ï¸ Running: $d"
            cd $d

            if nargo test; then
              echo "âœ… Passed: $d"
            else
              echo "âŒ Failed: $d"
              failed=1
            fi

            cd ..

          done

          if [[ $failed -eq 1 ]]; then
            echo "One or more tests failed"
            exit 1
          fi
          